title: Otavio Aranega # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  "👋 Hi, I'm Otávio, a programmer on a mission to turn my passion for coding into a career! With more than a year of self-study in Python and six months delving into system analysis and development at college. My journey involves crafting automation projects.By day, I'm a dedicated college student, absorbing the intricacies of system analysis. By night, you'll find me immersed in coding challenges, refining my Python expertise. Always hungry for knowledge, I complement my studies with a variety of online courses.
  <br><br>
  Second description 
  <br><br>
  <a href="www.linkedin.com/in/otavio-aranega-15957b249">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
